/*******************************************************************************
 * Copyright (c) 2011 The University of York.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Louis Rose - initial API and implementation
 ******************************************************************************/
package simulator.execution.model;

import java.io.Serializable;

import simulator.config.AlarmEvent;
import simulator.config.Event;
import simulator.execution.model.state.State;
import simulator.execution.model.state.VariableObserver;
import simulator.execution.model.state.VariableWithValueDelta;

public class SchedulableEvent implements VariableObserver, Serializable {

	// Generated by Eclipse
	private static final long serialVersionUID = 1506443280721493645L;
	
	private final String triggerName;
	private final String alarmTimeName;
	
	public SchedulableEvent(Event event) {
		this.triggerName   = ((AlarmEvent)event).getTrigger().getName();
		this.alarmTimeName = ((AlarmEvent)event).getAlarmTime().getName();
	}
	
	@Override
	public void variableChanged(VariableWithValueDelta variable, State state) {
		if (triggerName.equals(variable.getName()) || alarmTimeName.equals(variable.getName())) {
			final boolean valuesAreEqual = state.getValueOf(triggerName).equals(state.getValueOf(alarmTimeName));

			state.setAlarmRinging(valuesAreEqual);
		}
	}
					
}
