/*******************************************************************************
 * Copyright (c) 2011 The University of York.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Louis Rose - initial API and implementation
 ******************************************************************************/
package simulator.execution.model;

import java.io.Serializable;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;

public class State implements Serializable {

	// Generated by Eclipse
	private static final long serialVersionUID = -5877262571868562720L;
	
	private String displayText;
	private String indicatorText;
	private int currentModeIndex = 0;
	
	private final Map<VariableKey, Date> variableValues = new HashMap<VariableKey, Date>();
	private final int totalNumberOfModes;
	
	private transient List<ModeObserver> observers;
	
	public State() {
		this(1);
	}
	
	public State(int totalNumberOfModes) {
		this.totalNumberOfModes = totalNumberOfModes;
	}

	public String getDisplayText() {
		return displayText;
	}
	
	public void setDisplayText(String displayText) {
		this.displayText = displayText;
	}
	
	public String getIndicatorText() {
		return indicatorText;
	}
	
	public void setIndicatorText(String indicatorText) {
		this.indicatorText = indicatorText;
	}
	
	public Date getVariable(String variableName) {
		return variableValues.get(new VariableKey(currentModeIndex, variableName));
	}

	public void setVariable(String variableName, Date value) {
		variableValues.put(new VariableKey(currentModeIndex, variableName), value);
	}
	
	public int getCurrentModeIndex() {
		return currentModeIndex;
	}
	
	public void addModeObserver(ModeObserver observer) {
		getObservers().add(observer);
	}
	
	public void nextMode() {
		incrementModeIndex();
		notifyModeObservers();
	}

	private void incrementModeIndex() {
		currentModeIndex = (currentModeIndex + 1) % totalNumberOfModes;
	}
	
	private void notifyModeObservers() {
		for (ModeObserver observer : getObservers()) {
			observer.modeChanged(this);
		}
	}
	
	private List<ModeObserver> getObservers() {
		if (observers == null) {
			 observers = new LinkedList<ModeObserver>();
		}
		
		return observers;
	}
	
	
	private static class VariableKey {
		
		private final int modeIndex;
		private final String name;
		
		public VariableKey(int modeIndex, String name) {
			this.modeIndex = modeIndex;
			this.name = name;
		}
		
		@Override
		public boolean equals(Object o) {
			if (!(o instanceof VariableKey))
				return false;
			
			
			final VariableKey other = (VariableKey)o;
			
			return this.modeIndex == other.modeIndex &&
			       this.name.equals(other.name);
		}
		
		@Override
		public int hashCode() {
			return this.modeIndex + this.name.hashCode();
		}
		
		@Override
		public String toString() {
			return modeIndex + ": " + name;
		}	
	}
}
