/*******************************************************************************
 * Copyright (c) 2011 The University of York.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Louis Rose - initial API and implementation
 ******************************************************************************/
package simulator.model.actions;

import java.io.Serializable;

import simulator.model.Watch;


public class ChangeIndicatorAction implements Action, Serializable {
	
	// Generated by Eclipse
	private static final long serialVersionUID = 1744166233302345359L;

	@Override
	public void run(Watch watch) {
		watch.getAlarm().toggle();
	}
}
