/*******************************************************************************
 * Copyright (c) 2011 The University of York.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Louis Rose - initial API and implementation
 ******************************************************************************/
package simulator.model.actions;

import java.io.Serializable;

import simulator.model.Displayable;
import simulator.model.Watch;
import simulator.trace.Event;
import simulator.trace.TraceFactory;

public class ChangeDisplayAction implements Action, Serializable {

	// Generated by Eclipse
	private static final long serialVersionUID = 7677794761320829853L;
	
	private final Displayable displayable;
	
	public ChangeDisplayAction(simulator.config.Displayable displayable, Watch watch) {
		this.displayable = Displayable.resolve(displayable, watch);
	}
	
	@Override
	public void run(Watch watch) {
		final String textToDisplay = displayable.getText();
		
		watch.getDisplay().setText(textToDisplay);
		
		final Event event = TraceFactory.eINSTANCE.createEvent();
		event.setType("display");
		event.getParams().add(textToDisplay);
		watch.getTrace().getElements().add(event);
	}

}
