/*******************************************************************************
 * Copyright (c) 2011 The University of York.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Louis Rose - initial API and implementation
 ******************************************************************************/
package simulator.model.actions;

import java.io.Serializable;

import simulator.model.Watch;
import simulator.trace.Event;
import simulator.trace.TraceFactory;

public class NextModeAction implements Action, Serializable {
	
	// Generated by Eclipse
	private static final long serialVersionUID = 6713210770575261932L;
	
	@Override
	public void run(Watch watch) {
		final String nameOfNewMode = watch.getModes().nextMode();
		
		addTraceEvent(watch, nameOfNewMode);
	}

	private void addTraceEvent(Watch watch, final String nameOfNewMode) {
		final Event event = TraceFactory.eINSTANCE.createEvent();
		event.setType("mode");
		event.getParams().add(nameOfNewMode);
		watch.getTrace().getElements().add(event);
	}
}
