/*******************************************************************************
 * Copyright (c) 2011 The University of York.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Louis Rose - initial API and implementation
 ******************************************************************************/
package simulator.persistence;

public class SerializationException extends Error {

	// Generated by Eclipse
	private static final long serialVersionUID = 6685323040272561685L;

	public SerializationException(String message, Throwable cause) {
		super(message, cause);
	}
}
