/*******************************************************************************
 * Copyright (c) 2011 The University of York.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Louis Rose - initial API and implementation
 ******************************************************************************/
package simulator.model;

import java.io.Serializable;

public class AlarmIndicator implements Serializable {

	// Generated by Eclipse
	private static final long serialVersionUID = -127043715007718237L;
	
	private boolean isShowing = false;
	
	public void toggle() {
		isShowing = !isShowing;
	}
	
	public boolean isShowing() {
		return isShowing;
	}
}
