/*******************************************************************************
 * Copyright (c) 2011 The University of York.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Louis Rose - initial API and implementation
 ******************************************************************************/
package simulator.model;

import java.io.Serializable;
import java.util.Date;

public class Alarm implements Serializable {

	// Generated by Eclipse
	private static final long serialVersionUID = 6737853050410898651L;
	
	private final Date alarmTime;
	private final AlarmIndicator alarmIndicator = new AlarmIndicator();

	
	public Alarm(Date alarmTime) {
		this.alarmTime = alarmTime;
	}
	
	public AlarmIndicator getIndicator() {
		return alarmIndicator;
	}
	
	public boolean isAlarmTime(Date currentTime) {
		return currentTime.equals(alarmTime);
	}

	public void toggle() {
		alarmIndicator.toggle();
	}
}
