/*******************************************************************************
 * Copyright (c) 2011 The University of York.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Louis Rose - initial API and implementation
 ******************************************************************************/
package simulator.model;

import java.io.Serializable;

import simulator.model.actions.Action;

public class Button implements Serializable {

	// Generated by Eclipse
	private static final long serialVersionUID = -7173251772519131228L;

	private final String name;
	private final Action behaviour;
	
	private Watch watch;
	
	public Button(String name, Action behaviour) {
		this.name = name;
		this.behaviour = behaviour;
	}

	public String getName() {
		return name;
	}

	public Action getBehaviour() {
		return behaviour;
	}

	public void press() {
		behaviour.run(watch);
	}

	public void setWatch(Watch watch) {
		this.watch = watch;
	}
}
