/*******************************************************************************
 * Copyright (c) 2011 The University of York.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Louis Rose - initial API and implementation
 ******************************************************************************/
package simulator.model;

import java.io.Serializable;

import simulator.trace.Event;
import simulator.trace.TraceFactory;

public class ChangeDisplayAction implements EntryAction, Serializable {

	// Generated by Eclipse
	private static final long serialVersionUID = 7677794761320829853L;
	
	private final String text;
	
	public ChangeDisplayAction(String text) {
		this.text = text;
	}
	
	@Override
	public void run(Watch watch) {
		watch.getDisplay().setText(text);
		
		final Event event = TraceFactory.eINSTANCE.createEvent();
		event.setType("display");
		event.getParams().add(text);
		watch.getTrace().getElements().add(event);
	}

}
