/*******************************************************************************
 * Copyright (c) 2011 The University of York.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Louis Rose - initial API and implementation
 ******************************************************************************/
package simulator.model;

import java.io.Serializable;
import java.util.Date;

public class Display implements Serializable {

	// Generated by Eclipse
	private static final long serialVersionUID = -5226046197078335770L;
	
	private TimeFormatter timeFormatter = TimeFormatter.twelveHourFormatter;
	private String text = null;
	
	public String getText(Date currentTime) {
		if (text != null) {
			return text;
		} else {
			return timeFormatter.format(currentTime);
		}
	}
	
	public void setTimeFormatter(TimeFormatter timeFormatter) {
		this.timeFormatter = timeFormatter;
	}

	public void setText(String text) {
		this.text = text;
	}
}
