/*******************************************************************************
 * Copyright (c) 2011 The University of York.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Louis Rose - initial API and implementation
 ******************************************************************************/
package simulator.model;

import java.io.Serializable;

public class NumberAndString implements Serializable {

	// Generated by Eclipse
	private static final long serialVersionUID = 7630229661218064790L;
	
	private int number;
	private final String string;
	
	public NumberAndString(int number, String string) {
		this.number = number;
		this.string = string;
	}
	
	public void increment() {
		number++;
	}
	
	@Override
	public String toString() {
		return number + " - " + string;
	}
}
