/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package simulator.trace.impl;

import java.io.Serializable;

import org.eclipse.emf.ecore.EClass;

import simulator.trace.EnvironmentalChange;
import simulator.trace.TracePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Environmental Change</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * </p>
 *
 * @generated
 */
public class EnvironmentalChangeImpl extends TraceElementImpl implements EnvironmentalChange, Serializable {
	
	// Generated by Eclipse
	private static final long serialVersionUID = 4028297393704538430L;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnvironmentalChangeImpl() {
		super();
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EClass eStaticClass() {
		return TracePackage.Literals.ENVIRONMENTAL_CHANGE;
	}

} //EnvironmentalChangeImpl
