/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package simulator.trace.impl;

import java.io.Serializable;

import org.eclipse.emf.ecore.EClass;

import simulator.trace.Event;
import simulator.trace.TracePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Event</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * </p>
 *
 * @generated
 */
public class EventImpl extends TraceElementImpl implements Event, Serializable {
	
	// Generated by Eclipse
	private static final long serialVersionUID = 7907954908454622297L;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EventImpl() {
		super();
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EClass eStaticClass() {
		return TracePackage.Literals.EVENT;
	}

} //EventImpl
