/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package simulator.trace.impl;

import java.io.Serializable;

import org.eclipse.emf.ecore.EClass;

import simulator.trace.Stimulus;
import simulator.trace.TracePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Stimulus</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * </p>
 *
 * @generated
 */
public class StimulusImpl extends TraceElementImpl implements Stimulus, Serializable {
	
	// Generated by Eclipse
	private static final long serialVersionUID = -6893031320591132809L;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StimulusImpl() {
		super();
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EClass eStaticClass() {
		return TracePackage.Literals.STIMULUS;
	}

} //StimulusImpl
