/*******************************************************************************
 * Copyright (c) 2011 The University of York.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Louis Rose - initial API and implementation
 ******************************************************************************/
package simulator.execution.model.state;

import java.io.Serializable;
import java.util.Collection;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;

import simulator.execution.model.VariableWithValue;

public class VariableState implements Serializable {
	
	// Generated by Eclipse
	private static final long serialVersionUID = 4468173469341372878L;
	
	private final Map<VariableKey, Date> variableValues = new HashMap<VariableKey, Date>();

	public Date getValueOf(VariableKey key) {
		return variableValues.get(key);
	}
	
	public Collection<VariableWithValue> getValues(int currentModeIndex) {
		final List<VariableWithValue> variablesWithValues = new LinkedList<VariableWithValue>();
		
		for (Entry<VariableKey, Date> variableValue : variableValues.entrySet()) {
			if (variableValue.getKey().modeIndex == currentModeIndex) {
				variablesWithValues.add(new VariableWithValue(variableValue.getKey().variableName, variableValue.getValue()));
			}
		}
		
		return variablesWithValues;
	}

	public void setValueOf(VariableKey key, Date value) {
		variableValues.put(key, value);
	}
	
	public void initialiseValueOf(VariableKey key) {
		if (!variableValues.containsKey(key)) variableValues.put(key, new Date());
	}

	public VariableKey keyFor(int currentModeIndex, String variableName) {
		return new VariableKey(currentModeIndex, variableName);
	}
	
	static class VariableKey implements Serializable {
		
		// Generated by Eclipse
		private static final long serialVersionUID = -1345353674801988099L;
		
		private final int modeIndex;
		private final String variableName;
		
		public VariableKey(int modeIndex, String variableName) {
			this.modeIndex    = modeIndex;
			this.variableName = variableName;
		}
		
		@Override
		public boolean equals(Object o) {
			if (!(o instanceof VariableKey))
				return false;
			
			
			final VariableKey other = (VariableKey)o;
			
			return this.modeIndex == other.modeIndex &&
			       this.variableName.equals(other.variableName);
		}
		
		@Override
		public int hashCode() {
			return this.modeIndex + this.variableName.hashCode();
		}
		
		@Override
		public String toString() {
			return modeIndex + ": " + variableName;
		}	
	}
}